name: Build and Test

on: [push, pull_request]

jobs:
  build-vite-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        project: [jest-mock, vitest-mock]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ${{ matrix.project }}


    - name: Build project
      run: npm run build
      working-directory: ${{ matrix.project }}


    - name: Run tests
      run: npm test
      working-directory: ${{ matrix.project }}
